export const vars = {
  result: {
    code: 0,
    text: "",
  },
  vars: [
    {
      name: "VER",
      type: "STRING",
      value: "10.101",
      label: "Firmwareversion 40.",
      editable: false,
      visible: true,
      unit: "",
    },
    {
      name: "SER",
      type: "STRING",
      value: "35661",
      label: "Seriennummer",
      editable: false,
      visible: true,
      unit: "",
    },
    {
      name: "NLS",
      type: "ENUM",
      value: "Deutsch",
      label: "Sprache",
      editable: true,
      visible: true,
      "display-labels": ["Englisch", "Deutsch", "Koreanisch"],
      "display-values": ["01", "49", "02"],
      unit: "",
    },
    {
      name: "BRI",
      type: "INTEGER",
      value: "90",
      min: "0",
      max: "100",
      label: "Helligkeit",
      editable: true,
      visible: true,
      unit: "%",
    },
    {
      name: "LOG",
      type: "ENUM",
      value: "1 Sekunde",
      label: "Lograte",
      editable: true,
      visible: true,
      "display-labels": ["1 Sekunde", "5 Sekunden", "1 Minute", "15 Minuten"],
      "display-values": ["1", "5", "60", "900"],
      unit: "",
    },
    {
      name: "LOG:ENAB",
      type: "SWITCH",
      value: "true",
      label: "Aktivieren",
      editable: true,
      visible: true,
      unit: "",
    },
    {
      name: "LOG:EXP",
      type: "ACTION",
      value: "Ausführen",
      label: "Export",
      editable: true,
      visible: true,
      unit: "",
    },
    /* Sensor */
    {
      name: "PVR",
      type: "STRING",
      value: "40.201",
      label: "Firmwareversion 20.",
      editable: false,
      visible: true,
      unit: "",
    },
    {
      name: "PSR",
      type: "STRING",
      value: "42121",
      label: "Seriennummer",
      editable: false,
      visible: true,
      unit: ""
    },
    {
      name: "TP1",
      type: "FLOAT",
      value: "25.23",
      min: "0",
      max: "100",
      label: "Temperatur 1",
      editable: false,
      visible: true,
      unit: "°C",
    },
    {
      name: "TP1:W1L",
      type: "FLOAT",
      value: "-12",
      min: "0",
      max: "100",
      label: "Untere Warngrenze",
      editable: true,
      visible: true,
      unit: "°C",
    },
    {
      name: "TP1:W1H",
      type: "FLOAT",
      value: "120",
      min: "0",
      max: "140",
      label: "Obere Warngrenze",
      editable: true,
      visible: true,
      unit: "°C",
    },
    {
      name: "TMP",
      type: "FLOAT",
      value: "24.87",
      min: "0",
      max: "100",
      label: "Temperatur",
      editable: false,
      visible: true,
      unit: "°C",
    },
    {
      name: "TP2",
      type: "FLOAT",
      value: "25.23",
      min: "0",
      max: "100",
      label: "Temperatur 2",
      editable: false,
      visible: true,
      unit: "°C",
    },
  ],
};
